# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa9ffa02273461383e11fce0d2c52c82cbf1600ec4907017daa9b1b92c044679ab686b6bded22d2685ffd7918c2af53b88d49515a72dfa16ba792953e1037714

test:
  secret_key_base: 71fa8f34a94937272144eb5519f50738f4bdb506d2fa637a6e3f2385bb951dc2e241d3f30271d45267ce48247a0c670354d0b5f2a4d9e60fde78e57ea0f26fbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
